### ISSUE TITLE
is this a typo?

### ISSUE THREAD

**Issue by nagexiucai** [luna/luna-book#17]
In chapter basic-data-types, section [Maybe](https://github.com/luna/luna-book/blob/master/basic-datatypes.md#maybe):

    None   -> 'Didn't get a number.'

Shouldn't be 'Didn\'t get a number.' or 'Did not get a number' directly?

**Comment by kustosz** [comment]
Correct, that would break quotes! Also `None` is wrong there. The line should actually go:
`Nothing -> 'Did not get a number'`

**Comment by nagexiucai** [comment]
After the [Chinese translating](https://github.com/LunaCN/luna-book-zh-cn) of [luna-book](https://github.com/luna/luna-book), i feel that documents is poor and not systematic, i have trying to write  on [learnxinyminutes](https://github.com/nagexiucai/learnxinyminutes-docs/blob/master/luna.html.markdown), but Luna need illustrations indeed because of its distinctive visual representation. it seems that LearLunaIn20Minutes may be the first one not only just text. I am not sure if @adambard accept a PR with picture/image folder in addition :)

**Comment by kustosz** [comment]
Those efforts are great, thank you @nagexiucai!
What do you mean by the documentation being poor and unsistematic? What, in your opinion, needs fixing to make it more readable and understandable?

**Comment by nagexiucai** [comment]
:) I should change the words, i mean we must grade the documents, for example, a clear philosophy of design first, then a complete syntax note,  basic built-in functions/methods reference followed and so on.
Maybe i do not understand luna-lang so much now, i will work with it and write something like "Luna in Action" later, just give me some time.
