### ISSUE TITLE
I am glad to announce that the Chinese tanslation of luna-book complete a current version now!

### ISSUE THREAD

**Issue by nagexiucai** [luna/luna-book#18]
It is [here](https://github.com/LunaCN/luna-book-zh-cn) now.
if need to create a luna-book-zh-cn project on luna or make a zh-cn folder under luna-book?

**Comment by kustosz** [comment]
That's great! Gitbook supports multilingual books, so we can make it a subfolder in luna-book and then after going to docs.luna-lang.org everyone will be able to switch languages.

**Comment by nagexiucai** [comment]
Ok, that is good!
I am not familiar with gitbook, is [PR19](https://github.com/luna/luna-book/pull/19) right?

**Comment by nagexiucai** [comment]
Take time, i know there many things important need to be done, such as bugs. Because I am a pythoner, now i am going to learn Haskell and then can do something inside for luna. I have seen the best efforts of luna team, if i was familiar with Haskell i will do right now. Nowadays I am trying luna-studio, by "lunaInstaller" and "luna-manager install", but failed. I will describe at discord.

**Comment by kustosz** [comment]
Just reviewed it, there's some issues – tried to publish a branch on gitbook with that and it fails :) More info in the pull request

**Comment by nagexiucai** [comment]
All are ok now. Thank @kustosz very much.
